### ISSUE TITLE
User stealthily edited wiki page to record IP addresses

### ISSUE THREAD

**Issue by frozenpandaman** [wangqr/Aegisub#126]
https://github.com/wangqr/Aegisub/wiki/Compile-guide-for-Windows-(CMake,-MSVC)/_compare/a31b2c9f3b06c74837ae0984fc030f07177753e0...7a0255217f64d65ea3a7e3f30eaa76afc52f2775

What's up with this? I reverted it.

**Comment by IbarakiKasen** [comment]
Malicious commits are from auther `anokn <93703286+anokn@users.noreply.github.com>`. A google search suggests that this is a bot that changes download links to malware. Can we limit the edit permission of the project wiki? @wangqr

**Comment by wangqr** [comment]
done
