### ISSUE TITLE
wxwidgets 3.2 support

### ISSUE THREAD

**Issue by lae** [wangqr/Aegisub#146]
CMake fails to detect wxwidgets 3.2, which was released recently:

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindwxWidgets.cmake:984 (find_package_handle_standard_args)
  CMakeLists.txt:594 (find_package)


-- Configuring incomplete, errors occurred!
```

Any chance of supporting this? The release post suggests that not much work should need to be done to build against 3.2, but I don't really have any idea how true that is. 

https://www.wxwidgets.org/news/2022/07/wxwidgets-3.2.0-final-release/
https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.2.0/docs/changes.txt

**Comment by wangqr** [comment]
I haven't tried it yet, but https://github.com/Kitware/CMake/commit/2a19231d618482755e9aae981a65680bb1ec1050 suggests that CMake 3.24+ is needed to support wxWidgets 3.2

**Comment by lae** [comment]
Makes sense. I guess I'll wait for 3.24 to be released.

**Comment by lae** [comment]
After failing to use cmake from git, I realised I had set `wxWidgets_CONFIG_EXECUTABLE` to `/usr/bin/wx-config-gtk3` in the cmake flags in my build instructions for Aegisub, which disappeared/was replaced with `/usr/bin/wx-config`. After fixing that, Aegisub builds fine and seems to work against 3.2, at least in my cursory testing.
