### ISSUE TITLE
Update to wxWidgets 3.2?

### ISSUE THREAD

**Issue by WhiredPlanck** [wangqr/Aegisub#149]
wxWidgets finally releases its version 3.2 and brings a lot brilliant features that may benefit this project. Is there any plan to update to it?

**Comment by sergiomb2** [comment]
it builds with wxWidgets 3.2 (with autotools)

**Comment by WhiredPlanck** [comment]
> it builds with wxWidgets 3.2 (with autotools)

Thanks!
