### ISSUE TITLE
Error Message: bad cast

### ISSUE THREAD

**Issue by Intervencion** [wangqr/Aegisub#16]
Whenever I open an ass or I click on any line the error message pops up.

![Imgur](https://imgur.com/ISakfSj.png)

Also: Can't use "Find"
![Imgur](https://imgur.com/5reM0t8.png)

Curiously enough, it does not give any kind of error whatsoever on assdraw lines (\p1 lines). Tags are uncoloured also in all lines but assdraw lines.

**Comment by wangqr** [comment]
Which version are you using? Can you provide a sample ass for this?

**Comment by Intervencion** [comment]
Sure, I'm attaching the .ass here.

And I'm using Aegisub 3.3.0. .exe says version 0.0.0.9006 (downloaded a few hours ago, when my friend told me about this fork)

I'm using Avisynth as videosource (like I was doing on 3.2.2).

[[LlPnF] [Magic Kaito 1412] Episodi 1 [CAT]_cartells.zip](https://github.com/wangqr/Aegisub/files/3595902/LlPnF.Magic.Kaito.1412.Episodi.1.CAT._cartells.zip)

**Comment by wangqr** [comment]
Not reproducible here... Does Aegisub crash when you see this? If not, can you check `Help -> Log window` and see if there is any error?

**Comment by Intervencion** [comment]
I don't think I see any error https://pastebin.com/raw/ACvtcmhM

Doesn't add anything to the log when the error shows up

And nope, no crash or anything. Just anoying as hell error and the unavailibity to use the Find.

Gif below
https://i.imgur.com/vOkoyvX.mp4

**Comment by wangqr** [comment]
Seems that you are using the config file from an old version. I'm not sure if that causes any problem. But can you try:
* Exit Aegisub
* Rename the folder `C:\Users\<username>\AppData\Roaming\Aegisub` or move it to another location
* Start Aegisub, see if the issue still exists

**Comment by Intervencion** [comment]
Actually I just went and deleted all of Aegisub I found. Didn't help.

BTW it also errors inside the rar, both now and the first time I tried.

Nap time 😴 Please let me know if you find anything or if you require anything from me. I'm quite fond of this new version and I wish I will be able to continue using it

**Comment by wangqr** [comment]
Can you give the debug version a try and see if it gives the backtrace? https://ftp.wangqr.tk/aegisub/debug/Aegisub-r9009-Debug.zip

**Comment by Intervencion** [comment]
Sadly, the debug version is yelling at me with Sys. Errors.

I'm missing few DLL it seems:

- MSVCP140D.dll
- VCRUNTIME140D.dll
- ucrtbased.dll
- MSVCP140D.dll (again?)

**Comment by wangqr** [comment]
That's a missing VC Runtime error. You can extract the required dlls to Aegisub's folder from this zip:
> There was a link to the vc non-redistributable debug runtimes here. Removed since it is non-redistributable. You can download them from https://visualstudio.microsoft.com/

**Comment by Intervencion** [comment]
The DLL worked, and the debug version also is not yelling at me for the whatever error.

Find works too. Tags are coloured on non-assdraw lines now too. It's working fine.

**Comment by wangqr** [comment]
So the debug version doesn't have this issue? That's weird

**Comment by Intervencion** [comment]
Yep, debug seems to work. 

Log https://pastebin.com/raw/Yawm4KFQ

And good night Sir, thank you.

**Comment by MadokaAyukawa** [comment]
I get the same thing. I'm using rc1 without issues currently.

**Comment by wangqr** [comment]
Oh I can reproduce this now. Not sure what happened, but looks like a building/packaging issue.

rc1 is from d65643ddee3c1fe778e50155d0e9c8f3c6288430. Release is from 3 commits later, 5dd201bc2d4bf256ef226b824775837ea68ffd8c. No code is changed in between. And this issue also does not happen on my r9009 (81160b2ec07f9d5b512c249fcfb90b47fcf69a40) non-debug build, which is 3 commits after the release.

**Comment by wangqr** [comment]
@Intervencion If rc1 doesn't have this issue I suggest you use that one: https://ftp.wangqr.tk/aegisub/aegisub-win64-cmake-20190903-v3.3.0-rc1.zip . Because debug builds are for debug purpose and may complain or crash on non-fatal issues.

**Comment by wangqr** [comment]
I've just re-built the v3.3.0 again. Issue seems gone. The built binary is appended to the release.

**Comment by Intervencion** [comment]
All good so far here too👌  Thank you!
