### ISSUE TITLE
Find/Replace Errors

### ISSUE THREAD

**Issue by MadokaAyukawa** [wangqr/Aegisub#17]
Sometimes the find/replace function finds strings that do not match the input string. This is especially troublesome when trying to use the "Replace All" function. In the following screenshot, the sting "mature" is matched erroneously. I've encountered other strings that will do the same thing.

![image](https://user-images.githubusercontent.com/44476321/64661003-ae875b80-d3f7-11e9-91c4-d2a6afd0b9bb.png)

**Comment by wangqr** [comment]
Looks like something is wrong with the "Skip Override Tags". If I uncheck it, it seems fine.
