### ISSUE TITLE
wxTextCtrl in wxDialog "About Aegisub" has too low height

### ISSUE THREAD

**Issue by scx** [wangqr/Aegisub#19]
https://github.com/wangqr/Aegisub/commit/ad15c53fb169e76df28edeb7fb560639d1cde11b#diff-a09630cd54edec7b710d44c3ffc9c091R132
I see you have made some fixes for HiDPI support, which is good, but to be honest I'm not convinced of all these changes.
In my opinion the new About dialog is less readable.

Please take a look at the old version:
![aegisub-old](https://i.ibb.co/p35v9h2/aegisub-old.png)

And now look at the new one:
![aegisub-new](https://i.ibb.co/gdD3L9d/aegisub-new.png)

I understand that you wanted to get rid of fixed values, but in my opinion two lines of text are definitely not enough here.
I think it would be best to display 12 lines of text. This would give us very similar result to the old version of Aegisub.

I did some tests. See below for the results:

default:
![aegisub-test](https://i.ibb.co/MVdPPFF/aegisub-test.png)

8 lines:
![aegisub-test08](https://i.ibb.co/0Zb6whd/aegisub-test08.png)

12 lines:
![aegisub-test12](https://i.ibb.co/5r79w64/aegisub-test12.png)

16 lines:
![aegisub-test16](https://i.ibb.co/R2gHY3P/aegisub-test16.png)

And here is the patch ([aegisub-about.patch](https://pastebin.com/raw/ii4dKeZ7)):
```
diff --git a/src/dialog_about.cpp b/src/dialog_about.cpp
index b998c9a..b9d76a4 100644
--- a/src/dialog_about.cpp
+++ b/src/dialog_about.cpp
@@ -132,6 +132,8 @@ void ShowAboutDialog(wxWindow *parent) {
 	aboutString.Replace("(c)", wxString(copySymbol));
 
 	wxTextCtrl *textctrl = new wxTextCtrl(&d, -1, aboutString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE | wxTE_READONLY | wxBORDER_NONE);
+	int lines = 12;
+	textctrl->SetInitialSize(textctrl->GetSizeFromTextSize(-1, textctrl->GetTextExtent("X").GetHeight() * lines));
 
 	wxSizer *MainSizer = new wxBoxSizer(wxVERTICAL);
 	MainSizer->Add(new wxStaticBitmap(&d, -1, GETIMAGE(splash)), 0, wxCENTER, 0);
```

I can make a PR if you want.

See also:
https://docs.wxwidgets.org/3.0/classwx_control.html#a7f163dbbfa581a52192a94506784efc9
https://forums.wxwidgets.org/viewtopic.php?t=7346
https://stackoverflow.com/q/49468153

**Comment by scx** [comment]
Just one awful test I made:
[aegisub-about.zip](https://github.com/wangqr/Aegisub/files/3618931/aegisub-about.zip)

**Comment by wangqr** [comment]
Actually I only checked the Windows version, and wxMSW defaults to 10 lines which is fine in my opinion. I agree that 2 lines are too small. See https://trac.wxwidgets.org/ticket/18471#comment:1 .

I can do a quick fix that change the height on wxGTK (looks like you are using linux, correct me if i'm mistaken) or anything other than wxMSW (since I don't have a mac to test) to match the behavior on Windows.

**Comment by scx** [comment]
> Actually I only checked the Windows version, and wxMSW defaults to 10 lines which is fine in my opinion.

Agree, 10 lines is fine for me too.

> I agree that 2 lines are too small. See https://trac.wxwidgets.org/ticket/18471#comment:1 .

And what is worse, it doesn't even display scrollbar properly in GTK+3 backend (wxWidgets 3.0/Gtk+3) for such small box:
![aegisub-test-gtk3](https://i.ibb.co/g73fm5y/aegisub-test-gtk3.png)

> I can do a quick fix that change the height on wxGTK (looks like you are using linux, correct me if i'm mistaken) or anything other than wxMSW (since I don't have a mac to test) to match the behavior on Windows.

Yes, RHEL 7 as well as Fedora 30 and Ubuntu 18.04 LTS. The first two screenshots were taken from the wxWidgets 3.1/Gtk+2 version, and the others from the wxWidgets 3.0/Gtk+2 version.

Anyway, I think that `#ifndef __WXMSW__` would be fine. I also don't have access to the current macOS.

**Comment by scx** [comment]
## wxWidgets 3.0/Gtk+3

default:
![aegisub_gtk3_test](https://user-images.githubusercontent.com/510369/65007636-131a4d00-d907-11e9-8ff1-d8d228d59d11.png)

8 lines:
![aegisub_gtk3_test8](https://user-images.githubusercontent.com/510369/65007668-288f7700-d907-11e9-974b-cec1ef11e8fc.png)

12 lines:
![aegisub_gtk3_test12](https://user-images.githubusercontent.com/510369/65007672-2cbb9480-d907-11e9-97b7-4d75f5175af0.png)

16 lines:
![aegisub_gtk3_test16](https://user-images.githubusercontent.com/510369/65007678-2fb68500-d907-11e9-8dd7-c66b72c83ecd.png)

**Comment by wangqr** [comment]
Just checked the source code of wxGTK. Looks like they use same logic on wxGTK.

https://github.com/wxWidgets/wxWidgets/blob/e26d90028b497c75c541896df8a5d8ac6f4e8a3b/src/gtk/textctrl.cpp#L2058

**Comment by scx** [comment]
A cleaner solution:
```
diff --git a/src/dialog_about.cpp b/src/dialog_about.cpp
index b998c9a..d26f03e 100644
--- a/src/dialog_about.cpp
+++ b/src/dialog_about.cpp
@@ -132,6 +132,8 @@ void ShowAboutDialog(wxWindow *parent) {
 	aboutString.Replace("(c)", wxString(copySymbol));
 
 	wxTextCtrl *textctrl = new wxTextCtrl(&d, -1, aboutString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE | wxTE_READONLY | wxBORDER_NONE);
+	int lines = 10;
+	textctrl->SetInitialSize(textctrl->GetSizeFromTextSize(-1, textctrl->GetCharHeight() * lines));
 
 	wxSizer *MainSizer = new wxBoxSizer(wxVERTICAL);
 	MainSizer->Add(new wxStaticBitmap(&d, -1, GETIMAGE(splash)), 0, wxCENTER, 0);
```

**Comment by scx** [comment]
To be honest, I still don't know why the default code doesn't work as expected. Maybe this part is broken somehow?:
https://github.com/wxWidgets/wxWidgets/blob/v3.1.2/src/gtk/textctrl.cpp#L1309
https://developer.gnome.org/gtk3/stable/GtkTextBuffer.html#gtk-text-buffer-get-line-count

**Comment by wangqr** [comment]
upstream bug: https://trac.wxwidgets.org/ticket/18507

Now I'm not sure why your patch worked, since in my test, `SetInitialSize` and `SetSize` actually doesn't work (see the demo in the upstream ticket, you may add a log to verify that `GetBestSize` is giving correct result)

**Comment by wangqr** [comment]
So actually calling `SetInitialSize` with any size other than default (best) size will work.
