### ISSUE TITLE
Infinite recursion when loading video on macOS

### ISSUE THREAD

**Issue by cqjjjzr** [wangqr/Aegisub#21]
In 888be06 some changes have been made to video_display.cpp which causes infinite recursion.

The video display enables video/tool/cross tool when running VideoDisplay::Render() for the first time.

But when setting up the tool, the video box size is changed, which calls VideoDisplay::Render() again. So we need to set the tool BEFORE it modifies the box by "AddSeparator".

You can find a probable fix at https://github.com/cqjjjzr/Aegisub/commit/c03241a257a6225c004fcf117f2db8c10a32937e

**Comment by wangqr** [comment]
If modifying toolBar will call Render, is it better to put `tool = std::move(new_tool);` before `ClearTools`? Also I wonder if I should put `AddSeparator` after `Show(false)`, to eliminate unnecessary size updates.

**Comment by cqjjjzr** [comment]
1. Yes.

2. Probably, but I think it should be a minor problem.

**Comment by cqjjjzr** [comment]
And also, I wonder if you could give a review to #9 and consider reopening it.

**Comment by wangqr** [comment]
Yeah I see the update about this issue on #9 . I mean, I can receive notifications on closed issues. If you would like to reopen that issue to get more attention I can do that. But anyway I don't have time to help on that port.

**Comment by wangqr** [comment]
I cannot reproduce this issue here. Is there a reliable way to reproduce this issue (certain OS / DPI / video option)?

Provide a stack trace that shows the infinite recursion would also help.

**Comment by The-Asgore** [comment]
I can 100% reproduce this issue on a MacBook Air (13-inch,2017), with system version 10.15.4 (19E287), 1440×900 display, and also with opening any video even a blank video created by Aegisub itself.

Here is the Aegisub setting (actually it is default)

[config.txt](https://github.com/wangqr/Aegisub/files/4589646/config.txt)

-----------------------------------------------------------------------------------------------------------

And here is the process sample created by macOS Activity Monitor (what I did was creating a blank video and clicking the "Drag Subtitles" function icon):

[Sample of Aegisub.txt](https://github.com/wangqr/Aegisub/files/4589648/Sample.of.Aegisub.txt)

**Comment by wangqr** [comment]
Thanks. I was trying this on Windows
