### ISSUE TITLE
Open Dialogue Box Doesn't Remember Position

### ISSUE THREAD

**Issue by MadokaAyukawa** [wangqr/Aegisub#23]
Not a big issue, but the open dialogue box always opens in the upper left hand corner. In 3.2.2, I could move it to the middle of the screen, and it would remember to open there next time.

**Comment by wangqr** [comment]
You mean the open file dialog? Not reproducible here. Clicking both open and cancel will remember the position on my system (win 10.0.18362.356).

Actually no change is made about the open dialog, and it is handled by the system anyway. wxWidgets has been upgraded, which may cause some difference.

**Comment by MadokaAyukawa** [comment]
Sorry, selecting "Export Subtitle..." and then clicking on the "Export" button to open the "Export Subtitle file" dialog box will reset the "Open" and "Save" dialog box positions into the upper left hand corner. If it's handled by the system, then maybe this isn't an Aegisub issue. Present in 3.2.2. Feel free to close this issue.
