### ISSUE TITLE
aegisub-win64-cmake-20191025-r9047 打不开程序，报错

### ISSUE THREAD

**Issue by asxzwang** [wangqr/Aegisub#27]
由于找不到VCRUNTIME140_1.dll，无法继续执行代码。重新安装程序可能会解决此问题。

<a href="https://www.z4a.net/image/UN9zET"><img src="https://www.z4a.net/images/2019/10/27/13280d492d7299fe8.png" alt="13280d492d7299fe8.png" border="0" /></a>

**Comment by wangqr** [comment]
![图片](https://user-images.githubusercontent.com/8182182/67636174-3b04b500-f8a4-11e9-9d31-9b0db6d6a734.png)

请确保您正确开启了Windows Update，或前往 https://support.microsoft.com/zh-cn/help/2977003/the-latest-supported-visual-c-downloads 手工下载新版，所需的是2015-2019的vc_redist.x64.exe

**Comment by wangqr** [comment]
您好，上述方法是否能解决此issue？如果可以，请关闭此issue
