### ISSUE TITLE
Import configuration & hotkeys

### ISSUE THREAD

**Issue by Miayl** [wangqr/Aegisub#37]
Previous official Aegisub builds stored the configurations & hotkeys in .json files which allowed us to copy them to other builds. 

The Aegisub builds here seem to store the configurations & hotkeys in a different way. I already set up my own configurations & hotkeys in 3.3.0 and I would like to use to 3.3.1 without having to configure everything from scratch again. Is it possible to copy them?

**Comment by wangqr** [comment]
The configuration files are still in `%APPDATA%\Aegisub\`, where `%APPDATA%` is usually `C:\Users\<user>\AppData\Roaming\`. They are stored in `config.json` and `hotkey.json`

**Comment by Miayl** [comment]
Found them, thanks! Now they appear in 3.3.1 too.
