### ISSUE TITLE
Hope to add UTF-16LE with BOM support

### ISSUE THREAD

**Issue by Masaiki** [wangqr/Aegisub#38]
Now it can decode UTF-8 and GBK text. but in windows system, UTF-16 is also used widely. Though changing encodings is easy, it is also hard for people who don't know about encodings. So would you please add support of Unicode with BOM

**Comment by wangqr** [comment]
Is there a sample file? Or are you aware any software that is creating / able to load UTF-16LE ass files?

**Comment by Masaiki** [comment]
[sample file](https://drive.google.com/open?id=1po0AjAYDHTVtxLfflkQW0xbOT9SsU3uE)
software that is able to load UTF-16LE ass files like xy-VSFilter or [FontLoaderSub](https://github.com/yzwduck/FontLoaderSub)
FontLoaderSub judge encoding following the order
1. UTF-8, UTF-16 LE, UTF-16 BE with BOM，if BOM exists
2. UTF-8 without BOM
3. system encoding
4. UTF-16 LE。

**Comment by wangqr** [comment]
Aegisub should be able to detect the encoding (with uchardet) and manually specify if that doesn't work (File -> Open Subtitles with Charset). Some how both are not working.

**Comment by wangqr** [comment]
This should be fixed in latest nightly build [r9104](https://ftp.wangqr.tk/aegisub/aegisub-win64-cmake-20200404-r9104.zip).
