### ISSUE TITLE
Input Method Candidate doesn't follow with the cursor 

### ISSUE THREAD

**Issue by The-Asgore** [wangqr/Aegisub#42]
I' m using the 3.3.1 release in a win10 PC and the Microsoft IME pinyin. When I type in the edit box, the candidate always show on the left top of the screen, rather than following what I'm typing. And I also try the original Aegisub 3.2.2. Whatever I use the portable version or install version, the candidate cannot follow the cursor. Only the original Aegisub 3.2.2 for macos with using the build-in input method can follow the cursor rather than display on the left top of the screen (the default position if candidate doesn't follow the cursor).

**Comment by wangqr** [comment]
https://trac.wxwidgets.org/ticket/18759

**Comment by The-Asgore** [comment]
Thanks for your prompt reply. lol

**Comment by wangqr** [comment]
As this is an upstream issue, there's nothing to be done in Aegisub.

All nightly builds after r9123 will include relevant fix for wxWidgets.
