### ISSUE TITLE
Bug on macOS v3.3.1 aegisub: No reaction when using eyedropper and palettes | macOS版 v3.3.1 aegisub bug: 颜色吸管及调色盘功能无效

### ISSUE THREAD

**Issue by The-Asgore** [wangqr/Aegisub#45]
When clicking function icon "eyedropper tool" and also the two palettes on its right side, there is no any reaction.

**Comment by wangqr** [comment]
https://trac.wxwidgets.org/ticket/18545

**Comment by wangqr** [comment]
I've made a nightly build for [r9118](https://ftp.wangqr.tk/aegisub/aegisub-macos-20200507-r9118.dmg), which includes fixes for recent macOS issues. It will be nice if you can try it out. 

Given the amout of fixes, I have no plan backporting them to 3.3.1. Most likely they will just be included in next release. Or if there are more issues, maybe I'll make a 3.3.1.1 for mac.

**Comment by The-Asgore** [comment]
r9118 works well when dragging subtitle, eyedropper tool using and copying. 
Thx a lot and I will keep using the Aegisub both on Windows and macOS to find if there is anything need to be fixed to help your next release.
