### ISSUE TITLE
Copy lines not working on macOS

### ISSUE THREAD

**Issue by wangqr** [wangqr/Aegisub#46]
https://github.com/wangqr/Aegisub/issues/39#issuecomment-615535275

**Comment by Cyame** [comment]
I've updated to r9116 so far, and both the audio wave are good to use!
<img width="417" alt="截屏2020-05-07 上午10 32 12" src="https://user-images.githubusercontent.com/32809305/81248029-0f7e3680-904e-11ea-895d-d445faa17694.png">
But it seems still not able to copy&paste lines in it.
<img width="224" alt="截屏2020-05-07 上午10 29 40" src="https://user-images.githubusercontent.com/32809305/81247940-d219a900-904d-11ea-938b-2d20dc555054.png">
Could you tell the reason? Or you may need some logs? I'm happy to provide if you tell me which should I look for.

**Comment by wangqr** [comment]
I forgot this issue until I made the r9116 build and posted that reply in #39. So I created this issue to remind myself, and I haven't looked the details yet. I don't need log at the moment as I can reproduce this issue on my testing environment.

**Comment by Cyame** [comment]
Follow up: Okay I've try copy and paste seperately to check which function is not operating well. When I tried copy the dialogue lines from text, and it could be pasted to Aegisub, it's good. But it seems like the "copy" has some problems, for it could neither pasted to text nor Aegisub internally after "copied".

**Comment by wangqr** [comment]
https://trac.wxwidgets.org/ticket/18553

**Comment by wangqr** [comment]
There's no good way to workaround this wxOSX issue on Aegisub side. I've updated the mac build instruction, and made another r9118 build at https://ftp.wangqr.tk/aegisub/aegisub-macos-20200507-r9118.dmg , which should fix this issue

**Comment by Cyame** [comment]
Oh it is good to do copy and paste now! I'll keep focus using it to check if there's still something with bugs to help you know and fix them in the next release. Thx so much!
