### ISSUE TITLE
i want use with-system-luajit，but i don't know how luajit compiled in Lua 5.2 mode

### ISSUE THREAD

**Issue by glegender** [wangqr/Aegisub#48]
i want use with-system-luajit，but i don't know how luajit compiled in Lua 5.2 mode

./configure --with-system-luajit

checking whether LuaJIT is compiled in 5.2 mode... no
configure: error: in `/Users/xxxx/subtitle/Aegisub':
configure: error: LuaJIT must be compiled in Lua 5.2 mode

**Comment by qwe7989199** [comment]
Try to uncomment "**#CFLAGS+= -DLUAJIT_ENABLE_LUA52COMPAT**" in the makefile you can find before compiling luajit.

**Comment by glegender** [comment]
> Try to uncomment "**#CFLAGS+= -DLUAJIT_ENABLE_LUA52COMPAT**" in the makefile you can find before compiling luajit.

thanks
