### ISSUE TITLE
选择多行后保持窗口不消失 | Keep the window of "Select lines..." open

### ISSUE THREAD

**Issue by qwe7989199** [wangqr/Aegisub#49]
**A possible improvement on the "select lines ..." tool.**

Personally, I think the "**Select lines...**" tool should have the same working mode as the "**Find and Replace**" tool.   
  For example, if we want to select multiple lines with different conditions in one run of "Select lines...", it can not achieve this goal. 

![select line](https://user-images.githubusercontent.com/10990771/83266161-6fa36b00-a1fd-11ea-8bd2-143d819ef50f.gif)

**选择多行**工具有改进空间。
我个人觉得这个工具应该和**查找替换**工具以同样的方式运作。
而不是上图这样运行一次就直接消失。

**Comment by wangqr** [comment]
不确定您所说“类似查找替换工具”是指啥。但是为了让它不是运行一次就消失，可以在下面加一个"Apply"键，只执行操作而不关闭窗口？

**Comment by qwe7989199** [comment]
> 不确定您所说“类似查找替换工具”是指啥。但是为了让它不是运行一次就消失，可以在下面加一个"Apply"键，只执行操作而不关闭窗口？

就是这个意思。
