### ISSUE TITLE
What's the use of Command？

### ISSUE THREAD

**Issue by glegender** [wangqr/Aegisub#50]
hi，
What's the use of Command？Execute directly from the command line？

http://docs.aegisub.org/3.2/Commands/en_US/
![image](https://user-images.githubusercontent.com/19604753/83356330-0f94fc00-a398-11ea-9716-81b21ed4ca52.png)

**Comment by wangqr** [comment]
You can customize keyboard shortcuts for each command

**Comment by glegender** [comment]
> You can customize keyboard shortcuts for each command

thanks
