### ISSUE TITLE
[Bug Report]Audio Clip with noise in Version 3.3.1 / 3.3.1版本创建音频剪辑时有杂音

### ISSUE THREAD

**Issue by Cyame** [wangqr/Aegisub#56]
Hi, as title tells, I found the clip .wav file with full of noise while trying to create a audio clip using the quick menu in the subtitle lines. And it works good in 3.2.2. I didn't notice it before cuz I seldom use this function.

So maybe it's a bug that need to be fixed?

**Comment by wangqr** [comment]
是含有杂音还是仅有杂音？

如果可以，请提供示例原始媒体文件和字幕文件

**Comment by wangqr** [comment]
![img](https://user-images.githubusercontent.com/8182182/85991097-f3997000-b9c0-11ea-966d-e03e15c0d07d.png)
You can also try enabling this option and restart Aegisub, and see if this helps

**Comment by Cyame** [comment]
The option works! It is "with noise" rather than "noise only".
是带很大的杂音，比较影响听感（听力...）

↓音频样本（均使用331导出 一个勾选了选项一个没有←没有的那个真的很吵 请注意音量）
[audio.zip](https://github.com/wangqr/Aegisub/files/4844670/audio.zip)
↑audio sample

**Comment by wangqr** [comment]
麻烦协助测试一下 5f326cc87390ef6413af1a388093dc0aa1556c76 是否修正了此问题。nightly build可以在此处下载：https://ftp.wangqr.tk/aegisub/aegisub-win64-cmake-20200629-r9141.zip

如果问题仍然存在，请reopen本issue或回复告知。

测试时请记得测试未启用downmix to mono选项时的情况
