### ISSUE TITLE
_G.unicode.len(orgline.text_stripped:gsub("hello world",  "lua"))  这是错在哪里？

### ISSUE THREAD

**Issue by xiaomingguohe** [wangqr/Aegisub#58]
这段代码执行的时候出现如下错误：
Runtime error in template expression: Expected 1 arguments, got 2
Expression producing error: _G.unicode.len(orgline.text_stripped:gsub("hello world",  "lua"))
Template with expression: !_G.unicode.len(orgline.text_stripped:gsub("hello world",  "lua"))!

orgline.text_stripped:gsub("hello world",  "lua")  这个是有两个返回值吗？但是我测试了只有一个返回值

**Comment by wangqr** [comment]
似乎与 https://github.com/wangqr/Aegisub/issues/35#issuecomment-584026098 类似

**Comment by xiaomingguohe** [comment]
大佬真厉害，respect!!
