### ISSUE TITLE
大佬,3.3.1是支持多声道的噻? | XAudio2 not working properly on Win7

### ISSUE THREAD

**Issue by guokefeng** [wangqr/Aegisub#59]
Added XAudio2 audio player for Windows, which supports multi channel output
我设置了XAudio2,但是打开一段分左右声道的音频,结果还是单声道,求解决,另外有没有什么联系方式可以及时交流的啊,谢谢大佬

**Comment by wangqr** [comment]
![img](https://user-images.githubusercontent.com/8182182/85991097-f3997000-b9c0-11ea-966d-e03e15c0d07d.png)
为与旧版保持一致，默认会将音频混合成单声道。需要取消勾选图上的选项以使用原始多声道音频。

如果您使用AviSynth，还需将Avisynth down-mixer设置为None。

> 有没有什么联系方式可以及时交流的啊

您可以在git log中找到我的邮箱，但时效性跟开issue差不多

**Comment by guokefeng** [comment]
我和你图上是一样的设置,但还是单声道,只有左声道的音频打开播放结果两只耳机都有声音

**Comment by guokefeng** [comment]
> 
> 
> ![img](https://user-images.githubusercontent.com/8182182/85991097-f3997000-b9c0-11ea-966d-e03e15c0d07d.png)
> 为与旧版保持一致，默认会将音频混合成单声道。需要取消勾选图上的选项以使用原始多声道音频。
> 
> 如果您使用AviSynth，还需将Avisynth down-mixer设置为None。
> 
> > 有没有什么联系方式可以及时交流的啊
> 
> 您可以在git log中找到我的邮箱，但时效性跟开issue差不多
我和你图上是一样的设置,但还是单声道,只有左声道的音频打开播放结果两只耳机都有声音

**Comment by guokefeng** [comment]
> 
> 
> ![img](https://user-images.githubusercontent.com/8182182/85991097-f3997000-b9c0-11ea-966d-e03e15c0d07d.png)
> 为与旧版保持一致，默认会将音频混合成单声道。需要取消勾选图上的选项以使用原始多声道音频。
> 
> 如果您使用AviSynth，还需将Avisynth down-mixer设置为None。
> 
> > 有没有什么联系方式可以及时交流的啊
> 
> 您可以在git log中找到我的邮箱，但时效性跟开issue差不多

![1](https://user-images.githubusercontent.com/68358954/87622391-9e49b680-c755-11ea-8c4f-480adf6c693e.png)
我和你图上是一样的设置,但还是单声道,只有左声道的音频打开播放结果两只耳机都有声音

**Comment by wangqr** [comment]
有示例文件吗？

**Comment by wangqr** [comment]
[test_audio.zip](https://github.com/wangqr/Aegisub/files/4929182/test_audio.zip)

或者您可以用这个测试，这个在我这里是能区分左右的

**Comment by guokefeng** [comment]
> 
> 
> [test_audio.zip](https://github.com/wangqr/Aegisub/files/4929182/test_audio.zip)
> 
> 或者您可以用这个测试，这个在我这里是能区分左右的

还是单声道,我都要疯了

**Comment by wangqr** [comment]
您是能在两侧耳机听到左声道，还是只能在左耳机听到左声道？以及您使用其他视频播放器是正常的吗？

**Comment by guokefeng** [comment]
> 
> 
> 您是能在两侧耳机听到左声道，还是只能在左耳机听到左声道？

两侧耳机都能听到左声道,我用其他播放器比如potplayer就是正常的

**Comment by wangqr** [comment]
这就比较奇怪了。在Aegisub中，要么开启downmix（这时左右声道会被混在一起，任何一个耳机都可以听到所有声道），要么关闭downmix（这时对应耳机听到对应声道），但并没有代码使它能够在右耳机只听到左声道。

有一种判断方法是，在Aegisub中选取一段音频，然后在字幕列表中右键`Create audio clip`。此时存下来的wav文件就是Aegisub输出到系统音频的数据。然后您可以尝试用其他播放器播放这个wav文件，如果左右声道正常，那么大概率不是Aegisub的问题
![img](https://user-images.githubusercontent.com/8182182/87627068-e936e000-c6fb-11ea-8806-add981a080fd.png)

**Comment by guokefeng** [comment]
> 
> 
> 这就比较奇怪了。在Aegisub中，要么开启downmix（这时左右声道会被混在一起，任何一个耳机都可以听到所有声道），要么关闭downmix（这时对应耳机听到对应声道），但并没有代码使它能够在右耳机只听到左声道。
> 
> 有一种判断方法是，在Aegisub中选取一段音频，然后在字幕列表中右键`Create audio clip`。此时存下来的wav文件就是Aegisub输出到系统音频的数据。然后您可以尝试用其他播放器播放这个wav文件，如果左右声道正常，那么大概率不是Aegisub的问题
> ![img](https://user-images.githubusercontent.com/8182182/87627068-e936e000-c6fb-11ea-8806-add981a080fd.png)

我按照你所说的创建了,用potplayer播放左右声道正常,这个咋个办唉

**Comment by wangqr** [comment]
您的系统版本是？

**Comment by guokefeng** [comment]
> 
> 
> 您的系统版本是？

win7

**Comment by guokefeng** [comment]
> 
> 
> 您的系统版本是？

win7 64位

**Comment by wangqr** [comment]
我想确认一下是否是您系统中自带的XAudio2有bug。如果方便的话测试一下下述版本：

首先下载r9144： https://ftp.wangqr.tk/aegisub/aegisub-win64-cmake-20200704-r9144.zip
然后覆盖这些文件： [Aegisub-r9144-XAudio2-2.9.zip](https://github.com/wangqr/Aegisub/files/4929430/Aegisub-r9144-XAudio2-2.9.zip)

**Comment by guokefeng** [comment]
> 
> 
> 我想确认一下是否是您系统中自带的XAudio2有bug。如果方便的话测试一下下述版本：
> 
> 首先下载r9144： https://ftp.wangqr.tk/aegisub/aegisub-win64-cmake-20200704-r9144.zip
> 然后覆盖这些文件： [Aegisub-r9144-XAudio2-2.9.zip](https://github.com/wangqr/Aegisub/files/4929430/Aegisub-r9144-XAudio2-2.9.zip)

哇,覆盖了你这个就行了唉,大佬牛啊,谢谢,顺便问下系统中的XAudio2怎么修复唉

**Comment by wangqr** [comment]
您能检查一下在 C:\Windows\System32 中有哪些`XAudio2_*.dll`吗？XAudio2是DirectX的一部分，通常是随系统附带的

**Comment by guokefeng** [comment]
> 
> 
> 您能检查一下在 C:\Windows\System32 中有哪些`XAudio2_*.dll`吗？XAudio2是DirectX的一部分，通常是随系统附带的

XAudio2_*.dll一共有0-7

**Comment by wangqr** [comment]
看起来是正常的，我也不确定怎么修复。您可以尝试这个链接中的步骤更新DirectX： https://support.microsoft.com/zh-cn/help/179113/how-to-install-the-latest-version-of-directx ，但不一定有用

**Comment by guokefeng** [comment]
> 
> 
> 看起来是正常的，我也不确定怎么修复。您可以尝试这个链接中的步骤更新DirectX： https://support.microsoft.com/zh-cn/help/179113/how-to-install-the-latest-version-of-directx ，但不一定有用

好的，谢谢大佬耐心帮我解决问题，非常感谢

**Comment by Yang-Xijie** [comment]
请问macOS支持多声道吗？
我下载的最新的release v3.3.2 https://github.com/wangqr/Aegisub/releases/tag/v3.3.2

查看设置界面：
<img width="588" alt="image" src="https://user-images.githubusercontent.com/57952362/128604170-862031dd-8cbe-41a4-8e0b-5c1da6a09bdf.png">
音频播放器无法重新选择；关闭downmix。只能听到单声道

https://github.com/wangqr/Aegisub/issues/59#issuecomment-659153737
与此同样，导出后可以听到双声道音频
