### ISSUE TITLE
Text Malalignment

### ISSUE THREAD

**Issue by MadokaAyukawa** [wangqr/Aegisub#6]
In the Script Properties window, the "Default Aegisub file" is slightly skewed to the left so that the "D" is partially obscured.

When changing a hotkey, clicking on the hotkey will activate an input window. This window is shifted to the right, rather than opening up over the old hotkey as in 3.2.2.

Both of these issues are just cosmetic as fully functionality is retained.

**Comment by wangqr** [comment]
Upstream issue:
https://trac.wxwidgets.org/ticket/18472
https://trac.wxwidgets.org/ticket/18473 (fixed, will be included in builds later than 20190827)

**Comment by MadokaAyukawa** [comment]
Thanks for that.
