### ISSUE TITLE
Can't load .opus audio file from video

### ISSUE THREAD

**Issue by kedaitinh12** [wangqr/Aegisub#65]
I can't open .opus audio file from video .mkv
Ex file: https://drive.google.com/file/d/1DmcmGWfXzhASwW_AmgaDGUix1Ovx5a6R/view?usp=drivesdk

**Comment by wangqr** [comment]
The link you provided gives an error saying file not exist. Can you check that (could be the share permission)?
![screenshot](https://user-images.githubusercontent.com/8182182/90127540-59547800-dd33-11ea-9041-a307cc7aa17d.png)

I tested a mkv(avc+opus) downloaded from youtube with `youtube-dl`. Aegisub can open my test file without issue.

**Comment by kedaitinh12** [comment]
Link: https://drive.google.com/file/d/12EIlSi2YThKxAmuTjQ6CO7XHVixXjV9W/view?usp=drivesdk

Video open ok with directshowsource, but can't load audio, i can't do everything in aegisub with only video: sub, time,...

**Comment by kedaitinh12** [comment]
> The link you provided gives an error saying file not exist. Can you check that (could be the share permission)?
> ![screenshot](https://user-images.githubusercontent.com/8182182/90127540-59547800-dd33-11ea-9041-a307cc7aa17d.png)
> 
> I tested a mkv(avc+opus) downloaded from youtube with `youtube-dl`. Aegisub can open my test file without issue.

Link: https://drive.google.com/file/d/12EIlSi2YThKxAmuTjQ6CO7XHVixXjV9W/view?usp=drivesdk

Video open ok with directshowsource, but can't load audio, i can't do everything in aegisub with only video: sub, time,...

**Comment by wangqr** [comment]
You can load the audio with `Audio -> Open Audio File`, and select `All Files (*.*)` from the file format drop down menu.

FFMS2 won't load the video though, reporting `Invalid initial pts, dts, and duration`. The video you saw is actually loaded by AviSynth. I believe this specific mkv file is damaged. I can load it normally if I remux it with `ffmpeg -i Orion.mkv -c copy Orion.remux.mkv`

**Comment by kedaitinh12** [comment]
New ffms2
https://forum.doom9.org/showthread.php?p=1928993#post1928993

i think you can try it replaced old ffms2

**Comment by wangqr** [comment]
The binary build in release page still uses FFMS 2.23.1. I know there is a 2.40 release but it has multiple critical regression bugs. See the [FFMS2 bug](https://github.com/wangqr/Aegisub/labels/FFMS2%20bug) label.

**Comment by kedaitinh12** [comment]
> The binary build in release page still uses FFMS 2.23.1. I know there is a 2.40 release but it has multiple critical regression bugs. See the [FFMS2 bug](https://github.com/wangqr/Aegisub/labels/FFMS2%20bug) label.

no, it's not 2.40, it's is StvG ver with more stable than 2.40, see here:
https://forum.doom9.org/showthread.php?p=1921568#post1921568

**Comment by kedaitinh12** [comment]
I find out another ver of aegisub fixed all issues i made in here, thanks
https://github.com/TypesettingTools/Aegisub
