### ISSUE TITLE
Crash while loading video | 加载视频时闪退了

### ISSUE THREAD

**Issue by RollingSnack** [wangqr/Aegisub#67]
## Description | 描述
Crash happened when I try to load a video. Indexing seems to be fine.
And the `.ass` file automatically saved in the `recovered` folder can be opened without loading the video.
加载视频时闪退了，索引时似乎是正常的。
在不加载视频的情况下，我仍然可以打开自动保存在`recovered`文件夹下的`.ass`文件。

I also tried [r8942](http://plorkyeran.com/aegisub/) and it works.
我尝试用了[r8942](http://plorkyeran.com/aegisub/) 的版本，这个版本能正常加载。

This happens only on this video so far.
Could you please tell me what can I do to provide more information?
迄今为止，只发现在该视频上发生了这种情况。
请问我该如何提供更多有用的信息呢？

## My environment | 环境
**OS version**: Microsoft Windows 10 version 1903 (OS build 18362.959) x64-based
**Aegisub version**: [3.3.1 Release](https://github.com/wangqr/Aegisub/releases/tag/v3.3.1)
**Video info**: I used `ffmpeg -i` command to get it.
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\The highlight.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 01:07:17.05, start: 0.000000, bitrate: 1388 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1248 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
```

## Crash log | 日志
```
--- 20-08-04 19:31:08 ------------------
VER - 3.3.1
FTL - Beginning stack dump for "Fatal exception": 
End of stack dump.
----------------------------------------
```

**Comment by wangqr** [comment]
您用的是32位版还是64位版？

**Comment by wangqr** [comment]
如果是32位版，有4GiB内存的限制，在3.3.1中默认加载全声道时内存使用量会比3.3.0大。如果您是使用的32位版，可以测试一下r9157（ https://ftp.wangqr.tk/aegisub/aegisub-win32-cmake-20200721-r9157.zip ）在打开相关文件时是否有内存不足警告，以及可尝试3.3.0是否正常。

如果你用的64位版请忽略上述内容

**Comment by RollingSnack** [comment]
> 
> 
> 如果是32位版，有4GiB内存的限制，在3.3.1中默认加载全声道时内存使用量会比3.3.0大。如果您是使用的32位版，可以测试一下r9157（ https://ftp.wangqr.tk/aegisub/aegisub-win32-cmake-20200721-r9157.zip ）在打开相关文件时是否有内存不足警告，以及可尝试3.3.0是否正常。
> 
> 如果你用的64位版请忽略上述内容

Thank you for your help. I used the 3.3.1 32-bit version before.
感谢帮助。我之前用的确实是3.3.1的32bit版本。
As you said, it should be the memory problem.
如你所述，应该就是内存问题。

### Other versions' test results | 其他版本的测试结果
- **3.3.0-win32-rebuild20191111**: Works.
- **3.3.1-win64**: Works.
- **dev version [r9157](https://ftp.wangqr.tk/aegisub/)-win32**: All 3 solutions listed below are effective. | 下述3个方法都有效。
```
Unable to create RAM audio cache: 32-bit memory limit exceeded. Fallback to hard disk cache.
Possible solutions:
- Use 64-bit version
- Turn off cache or switch to hard disk cache in Preferences -> Advanced -> Audio -> Cache -> Cache type
- Enable channel downmix in Preferences -> Advanced -> Audio
```

The problem seems to be solved before, and this issue could be closed.
看来问题之前就已经解决了，那么这个issue可以关闭了。抱歉在反馈前，我没搜索到类似的反馈。
