### ISSUE TITLE
Align Subtitle to Video by Key Points

### ISSUE THREAD

**Issue by MadokaAyukawa** [wangqr/Aegisub#7]
I haven't figured out how to use this feature. I see that I can get the X,Y coordinates and color of the key point, but is it saved into memory so I can paste it elsewhere? Also, is there a command for it to bind to a hot key?

This is just cosmetic, but the tool tip for it has a period at the end. None of the other tool tips have a period at the end.

**Comment by wangqr** [comment]
The idea of this feature is automatically generate the start / end time from a existing hard sub within the video. When you click the button, a window will pop up, so you can select the location of hard sub in the image. Then it will automatically check the color difference of the selected pixel location in previous / subsequent frames, until the difference is greater than "tolerance" value. The start / end time of current line will be modified to align (in time domain) with the hard sub.

The command name is `time/align`. You can bind hot key to it.

**Comment by MadokaAyukawa** [comment]
Thank you. I did not realize it was for hard subs. Very nice.
