### ISSUE TITLE
[Bug Report][version 3.3.1]首次开启时视频读取出现绿条/噪声 | The video is being with noises opened at the first time

### ISSUE THREAD

**Issue by Cyame** [wangqr/Aegisub#71]
情况如图：
![image](https://user-images.githubusercontent.com/32809305/92208917-b66cc500-eebe-11ea-82f7-24d7aac42589.png)

并不是第一次出现，大概有4-5次。其中还有用FFMPEG重新编码过的视频...其他使用3.2.2的朋友都是可以正常打开的，我这边会发生这种现象。

**重启后可修复该问题**

查看了一下Open Issue发现没有类似的问题...但这个状况是我更换PC之后才发生的，在之前的电脑上安装的3.3.1和中间的R版本均未出现此类问题。

---

附设备信息：

![image](https://user-images.githubusercontent.com/32809305/92209349-6d694080-eebf-11ea-841e-6c911fa85435.png)

显卡是该型号自带的GTX 2060.

**Comment by wangqr** [comment]
鼠标放在视频上时的十字叉能正常显示吗？如果不能，那么大概率是显卡驱动问题。wxMSW的OpenGL确实更改过默认参数，见#55

**Comment by wangqr** [comment]
如果怀疑#55，可以先尝试r9142或之后的开发版本，可以从 https://ftp.wangqr.tk/aegisub/ 获取

**Comment by Cyame** [comment]
> 鼠标放在视频上时的十字叉能正常显示吗？如果不能，那么大概率是显卡驱动问题。wxMSW的OpenGL确实更改过默认参数，见#55

确实不能，目前已移动至r9157，目前使用暂未出现问题。感谢答复！如有其他情况会再开。
