### ISSUE TITLE
cannot load a 32 bit dll in 64 bit avisynth DirectShowSource.dll

### ISSUE THREAD

**Issue by stevennight** [wangqr/Aegisub#78]
version is aegisub-win64-cmake-20200721-r9157

**Comment by wangqr** [comment]
That's a packaging issue. You can download the 64 bit DirectShowSource.dll from [AviSynth/AviSynthPlus](https://github.com/AviSynth/AviSynthPlus/releases). It's in ` AviSynthPlus_3.6.1_20200619-filesonly/x64/plugins/DirectShowSource.dll`. Extract that dll and override the dll in Aegisub folder.

**Comment by wangqr** [comment]
As 3.3.2 has released, I'll close this issue and left r9157 nightly build as is.
