### ISSUE TITLE
travis-ci.org will be closed on December 31st, 2020

### ISSUE THREAD

**Issue by wangqr** [wangqr/Aegisub#79]
Consider migrating to travis-ci.com or GHA

**Comment by Rassyan** [comment]
Maybe you can migrate to gitlab-ci.
The VideoLAN group running a public free gitlab and provide free ci.
https://code.videolan.org/

**Comment by Fuseteam** [comment]
ohw this one has it's own issue tab

**Comment by Fuseteam** [comment]
i am attempting to make it run on GHA but it fails at configure

**Comment by wangqr** [comment]
Migrating to travis-ci.com seems to be the easiest option. Make a PR if you think other CI offer better features.
