### ISSUE TITLE
"Number of Characters in the Longest Line of this Subtitle" Box

### ISSUE THREAD

**Issue by MadokaAyukawa** [wangqr/Aegisub#8]
I use this box to help me decide when I need to add a line break. However, as it is currently positioned at the end, past the Effect box, it is not in my field of vision on my widescreen monitor. I rarely use the Actor and Effects field and have not seen many people use them as well.

I think if this box were moved to just after the Edit button for the Styles, just before the Actor field, it would be more in the middle of the screen when timing and editing subtitles, and it would be more evident when lines are too long.

**Comment by wangqr** [comment]
It was added in 422cfb153faa96ac1610d60e846d344f11bfb8f3, after actor and effect box, so it's there on the right side.

> I rarely use the Actor and Effects field and have not seen many people use them as well.

Actor is for quickly setting style for each person and can be loaded from text script as long as it is colon separated. Effect field is for the [karaoke template](https://www.google.com/search?q=aegisub+karaoke+template), which is mainly (ab)used for generating special effects. Both are quite important and we use it frequently.

> I think if this box were moved to just after the Edit button for the Styles, just before the Actor field

This can be done by simply moving up [line 145-148 of subs_edit_box.cpp](https://github.com/wangqr/Aegisub/blob/4a3689d6e70bee375a34def947bf58a991e699b4/src/subs_edit_box.cpp#L145-L148). I'm not going to make this change in this repo by now, for several reasons:
* It has been there for 7 years and people in my group are used to that. Making it customizable makes more sense than just changing the position by hardcode.
* I personally think that it is a bad design to place a read-only field between editable properties.
* Charactor count itself is not a common practise either. Mordern editors solve the overlong line problem by using vertical guidelines. It doesn't fit in our scene quite well (ass tags take up space; font in the editor box and used by sub are not monospace). But at least, rendering `\N` as newline is enough to quickly spot any overlong lines. So we may just implement this feature and get rid of the char counter.

**Comment by MadokaAyukawa** [comment]
Thank you for your explanation. I see where I can move those lines, but I don't know how to use the resulting edited file. Can I put it in the Aegisub folder somewhere and have it over-ride the hard coded defaults, or do I have to build Aegisub myself (as I don't know how to do that).

**Comment by wangqr** [comment]
Yes you need to build it by yourself. There is build insturction in the README.md, either using CMake from this fork, or directly using Visual Studio sln described in the [original repo](https://github.com/Aegisub/Aegisub/blob/master/README.md#windows).

Since this modification is not complicated, here's a build by me (dependencies not included, you need [this one](https://ftp.wangqr.tk/aegisub/aegisub-win64-cmake-20190824.zip) first): [Aegisub.zip](https://github.com/wangqr/Aegisub/files/3538417/Aegisub.zip)
But I won't be able to build this change after making further modifications. In other words, I won't update the above file.

**Comment by MadokaAyukawa** [comment]
Thank you very much. That may mean I'm forever locked into this build now. LOL.
