### ISSUE TITLE
Crashes will happened when opening new audio file while playing audio

### ISSUE THREAD

**Issue by Hshan7** [wangqr/Aegisub#83]

**Comment by wangqr** [comment]
Can you provide:
* The OS you are using
* The version of Aegisub you are using (can be found at title bar)
* A screenshot of the `Preferences -> Advanced -> Audio` page

**Comment by Hshan7** [comment]
> Can you provide:
> 
> * The OS you are using
> * The version of Aegisub you are using (can be found at title bar)
> * A screenshot of the `Preferences -> Advanced -> Audio` page

操作系统是win10家庭版
Aegisub版本为 3.3.1
高级-音频-音频播放器选项为 XAudio2

经测试发现仅在音频播放器为XAudio2时，这个错误才会稳定发生。

**Comment by wangqr** [comment]
该问题可能已在 1fda1d2b056dabd5643dc0316a8e750d5a7c290a 中修复，您方便测试一下[3.3.2版](https://github.com/wangqr/Aegisub/releases/tag/v3.3.2)吗？

**Comment by Hshan7** [comment]
> 该问题可能已在 [1fda1d2](https://github.com/wangqr/Aegisub/commit/1fda1d2b056dabd5643dc0316a8e750d5a7c290a) 中修复，您方便测试一下[3.3.2版](https://github.com/wangqr/Aegisub/releases/tag/v3.3.2)吗？

在3.2.2版本中没有发现类似问题，感谢回答
