### ISSUE TITLE
crash with vsfiltermod

### ISSUE THREAD

**Issue by realfinder** [wangqr/Aegisub#92]
if the .ass file has
Update Details: 
in [Script Info]

if the subtitles provider is vsfiltermod (default) and if you have both video and subtitle it will crash with this

![image](https://user-images.githubusercontent.com/2512153/108183169-e2050400-711a-11eb-9ae3-ccfc1d7f3b0c.png)

then
![image](https://user-images.githubusercontent.com/2512153/108183356-0bbe2b00-711b-11eb-82ae-086dbaf24083.png)

test file
[track3_eng.zip](https://github.com/wangqr/Aegisub/files/5994611/track3_eng.zip)

**Comment by Masaiki** [comment]
fixed.
You can find the lastest version on https://github.com/Masaiki/VSFilterMod/actions
By the way, this issue should be opened on the VSFilterMod repo.

**Comment by wangqr** [comment]
FYI: The VsFilterMod.dll included in binary releases is from sorayuki/VSFilterMod

**Comment by Masaiki** [comment]
> FYI: The VsFilterMod.dll included in binary releases is from sorayuki/VSFilterMod

do you have interest in changing VSFilterMod binary release to my fork's?

**Comment by realfinder** [comment]
@Masaiki 
can you make a .dll binary release? I didn't see you build one https://github.com/Masaiki/VSFilterMod/releases

**Comment by Masaiki** [comment]
> @Masaiki
> can you make a .dll binary release? I didn't see you build one https://github.com/Masaiki/VSFilterMod/releases

Open the workflow runs, you will find the .dll binary release under Artifacts builded by github actions.

**Comment by wangqr** [comment]
> do you have interest in changing VSFilterMod binary release to my fork's?

Can you create a PR at sorayuki fork to see if that repo is still maintained?

**Comment by Masaiki** [comment]
> > do you have interest in changing VSFilterMod binary release to my fork's?
> 
> Can you create a PR at sorayuki fork to see if that repo is still maintained?

My commits have been merged.

**Comment by wangqr** [comment]
> My commits have been merged.

Thanks for the effort! Binary builds from r9185 will use r5.2.4 from sorayuki fork.
