### ISSUE TITLE
No audio !! Linux

### ISSUE THREAD

**Issue by adolfotregosa** [wangqr/Aegisub#94]
under linux, aegisub outputs no audio if "enable-remixing = no" is configured in /etc/pulse/daemon.conf which is basically obligatory so pulseaudio does not output stereo sources on the rear speakers at the same time if you have system audio output configured to 5.1 or more channels. 

Any suggestion on how to fix this ??

**Comment by wangqr** [comment]
Possibly related: https://bugs.freedesktop.org/show_bug.cgi?id=62588
It suggests setting `enable-remixing=yes` and `remixing-use-all-sink-channels=no`.

**Comment by wangqr** [comment]
Also, currently Aegisub always downmix audio to mono except on Windows XAudio2 output.

**Comment by adolfotregosa** [comment]
remixing-use-all-sink-channels=no seams to work fine. Thank you for the suggestion
