### ISSUE TITLE
[Feature Request] Total Time of Line in the Video Section

### ISSUE THREAD

**Issue by MadokaAyukawa** [wangqr/Aegisub#99]
Is it possible to add this feature from the Daydream Cafe Edition that gives the total time of the line?

![image](https://user-images.githubusercontent.com/44476321/114093234-b4614f00-986f-11eb-8562-63e16b2bf153.png)

**Comment by wangqr** [comment]
It seems that the third value is the duration of the line, which is already shown above the subtitle edit box. Is there a use case why you need it also shown in the video section?

https://github.com/Ristellise/AegisubDC/blob/master/src/video_box.cpp#L136

**Comment by MadokaAyukawa** [comment]
I use it for transforms. When I find the frame I want the transform to start at, I get the time from the video section as the first number. For the transforms that I want to extend to the end of the line, it's handy to have that information in the same box/area where I can get all the variables I need for the tag.
